name: rest node nestjs

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - src/**
      - .github/workflows/**

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    - name: Build
      run: npm run build --if-present
    # - name: Test
    #  run: npm test